version: '3'
services:
  jupyter:
    build: .
    ports:
      - "8888:8888"
    volumes:
      - .:/home/jacopomanenti/algo/Privacy-Preserving-Algorithmic-Trading-with-Zero-Knowledge-Proofs
    environment:
      - JUPYTER_ENABLE_LAB=yes