{
 "title": "Batch: Binary Classification Metrics Dashboard",
 "tags": [
  "machine-learning",
  "classification",
  "Batch"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Total Samples Count",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "query": "from(bucket: \"my_bucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"batch_binary_metrics\")\n  |> filter(fn: (r) => r[\"_field\"] == \"samples_count\")\n  |> sum()"
    }
   ]
  },
  {
   "title": "Current Metrics",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"my_bucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"batch_binary_metrics\")\n  |> filter(fn: (r) => r[\"_field\"] == \"accuracy\" or r[\"_field\"] == \"f1\" or r[\"_field\"] == \"precision\" or r[\"_field\"] == \"recall\")\n  |> last()"
    }
   ]
  },
  {
   "title": "Classification Metrics Over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "query": "from(bucket: \"my_bucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"batch_binary_metrics\")\n  |> filter(fn: (r) => r[\"_field\"] == \"accuracy\" or r[\"_field\"] == \"f1\" or r[\"_field\"] == \"precision\" or r[\"_field\"] == \"recall\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)"
    }
   ]
  }
 ]
}